name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Installer Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd docker docker.io
          curl -fsSL https://get.docker.com | sudo bash

      - name: Build Docker image
        run: |
          docker build -t mon-app-node .

      - name: Vérifier l'image Docker
        run: |
          docker images

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Installer Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd docker docker.io
          curl -fsSL https://get.docker.com | sudo bash

      - name: Lancer le conteneur
        run: |
          docker run -d -p 8080:8080 --name test-container mon-app-node
          sleep 5  # Laisse le temps au serveur de démarrer

      - name: Vérifier que l'application répond
        run: |
          curl -f http://localhost:8080 || (docker logs test-container && exit 1)

      - name: Arrêter et supprimer le conteneur
        run: |
          docker stop test-container
          docker rm test-container

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Installer Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd docker docker.io
          curl -fsSL https://get.docker.com | sudo bash

      - name: Se connecter à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag et Push l'image Docker
        run: |
          docker tag mon-app-node ${{ secrets.DOCKER_USERNAME }}/mon-app-node:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mon-app-node:latest
